version: "3.7"

services:
    # image project
    app:
        container_name: filme
        build:
            args:
                user: faker
                uid: 1001
            context: ./
            dockerfile: Dockerfile
        image: especializati/laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./docker/php/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
            - ./:/var/www
        # depends_on:
        #     - redis
        networks:
            - redeFilmes
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8889:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
            - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
        networks:
            - redeFilmes

    # db mysql
    db:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - redeFilmes

    # queue
    # queue:
    #     image: especializati/laravel9-app
    #     restart: unless-stopped
    #     command: "php artisan queue:work"
    #     volumes:
    #         - ./:/var/www
    #     depends_on:
    #         # - redis
    #         - app
    #     networks:
    #         - redeFilmes

    # redis
    # redis:
    #     image: redis:latest
    #     networks:
    #         - redeFilmes

networks:
    redeFilmes:
        driver: bridge
